import type { Holding } from "../types";

export const HOLDINGS: Holding[] = [
  /* ── SUBSIDIARIES / PRIVATE EQUITY ────────────────────── */
  {
    id: "HIG",
    name: "Heirs Insurance Group",
    assetClass: "Private Equity",
    sector: "Insurance",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Holdings Ltd",
    quantity: 1,
    costPrice: 98_400,
    costBasis: 98_400,
    marketValue: 118_500,
    ytdReturn: 0.145,
    beta: 0.82,
    dividendYield: 0.038,
  },
  {
    id: "HLA",
    name: "Heirs Life Assurance",
    assetClass: "Private Equity",
    sector: "Insurance",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Holdings Ltd",
    quantity: 1,
    costPrice: 61_200,
    costBasis: 61_200,
    marketValue: 72_400,
    ytdReturn: 0.128,
    beta: 0.78,
    dividendYield: 0.032,
  },
  {
    id: "HET",
    name: "Heirs Energies / Tenoil",
    assetClass: "Private Equity",
    sector: "Energy",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Holdings Ltd",
    quantity: 1,
    costPrice: 84_600,
    costBasis: 84_600,
    marketValue: 98_200,
    ytdReturn: 0.16,
    beta: 1.05,
  },
  {
    id: "HTG",
    name: "Heirs Technologies",
    assetClass: "Private Equity",
    sector: "Technology",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Holdings Ltd",
    quantity: 1,
    costPrice: 22_500,
    costBasis: 22_500,
    marketValue: 28_000,
    ytdReturn: 0.22,
    beta: 1.15,
  },
  {
    id: "AGF3",
    name: "Africa Growth Fund III",
    assetClass: "Private Equity",
    sector: "Diversified PE",
    geography: "Pan-Africa",
    currency: "USD",
    issuer: "African Capital Alliance",
    quantity: 1,
    costPrice: 56_800,
    costBasis: 56_800,
    marketValue: 64_000,
    ytdReturn: 0.108,
    beta: 0.88,
  },

  /* ── LISTED EQUITIES ───────────────────────────────────── */
  {
    id: "TCP",
    name: "Transcorp Plc",
    assetClass: "Equity",
    sector: "Conglomerate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Transcorp Plc",
    quantity: 8_200_000_000,
    costPrice: 5.82,
    costBasis: 47_724,
    marketValue: 68_000,
    marketPrice: 8.29,
    ytdReturn: 0.184,
    beta: 1.12,
    dividendYield: 0.021,
  },
  {
    id: "TCH",
    name: "Transcorp Hotels Plc",
    assetClass: "Equity",
    sector: "Hospitality",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Transcorp Hotels Plc",
    quantity: 3_750_000_000,
    costPrice: 8.44,
    costBasis: 31_650,
    marketValue: 42_000,
    marketPrice: 11.2,
    ytdReturn: 0.134,
    beta: 0.94,
    dividendYield: 0.018,
  },
  {
    id: "UCA",
    name: "United Capital Plc",
    assetClass: "Equity",
    sector: "Financial Services",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "United Capital Plc",
    quantity: 1_580_000_000,
    costPrice: 12.68,
    costBasis: 20_034,
    marketValue: 24_000,
    marketPrice: 15.19,
    ytdReturn: 0.098,
    beta: 0.96,
    dividendYield: 0.042,
  },
  {
    id: "APG",
    name: "Africa Prudential Plc",
    assetClass: "Equity",
    sector: "Financial Services",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Africa Prudential Plc",
    quantity: 580_000_000,
    costPrice: 13.4,
    costBasis: 7_772,
    marketValue: 9_500,
    marketPrice: 16.38,
    ytdReturn: 0.062,
    beta: 0.78,
    dividendYield: 0.055,
  },
  {
    id: "HBK",
    name: "Heritage Bank",
    assetClass: "Equity",
    sector: "Banking",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heritage Bank Plc",
    quantity: 1_820_000_000,
    costPrice: 7.1,
    costBasis: 12_922,
    marketValue: 16_500,
    marketPrice: 9.07,
    ytdReturn: 0.075,
    beta: 1.08,
    dividendYield: 0.028,
  },

  /* ── REAL ESTATE ───────────────────────────────────────── */
  {
    id: "HPL",
    name: "Heirs Place HQ Lagos",
    assetClass: "Real Estate",
    sector: "Commercial Real Estate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Real Estate Ltd",
    quantity: 1,
    costPrice: 62_400,
    costBasis: 62_400,
    marketValue: 72_000,
    ytdReturn: 0.094,
    beta: 0.42,
  },
  {
    id: "HTA",
    name: "Heirs Tower Abuja",
    assetClass: "Real Estate",
    sector: "Commercial Real Estate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Real Estate Ltd",
    quantity: 1,
    costPrice: 38_600,
    costBasis: 38_600,
    marketValue: 46_500,
    ytdReturn: 0.105,
    beta: 0.38,
  },

  /* ── FIXED INCOME ──────────────────────────────────────── */
  {
    id: "FGNB31",
    name: "FGN Bond 2031 (15.5%)",
    assetClass: "Fixed Income",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Federal Govt. of Nigeria",
    quantity: 1_000_000,
    costPrice: 76_200,
    costBasis: 76_200,
    marketValue: 78_400,
    marketPrice: 78_400,
    ytdReturn: 0.062,
    beta: 0.08,
    dividendYield: 0.155,
  },
  {
    id: "FGNB33",
    name: "FGN Bond 2033 (16.25%)",
    assetClass: "Fixed Income",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Federal Govt. of Nigeria",
    quantity: 800_000,
    costPrice: 27_800,
    costBasis: 27_800,
    marketValue: 23_400,
    marketPrice: 29_250,
    ytdReturn: 0.054,
    beta: 0.09,
    dividendYield: 0.1625,
  },
  {
    id: "DGB26",
    name: "Dangote Industries Bond 2026",
    assetClass: "Fixed Income",
    sector: "Corporate",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Dangote Industries Ltd",
    quantity: 250_000,
    costPrice: 72_400,
    costBasis: 72_400,
    marketValue: 18_500,
    marketPrice: 74_000,
    ytdReturn: 0.041,
    beta: 0.14,
    dividendYield: 0.1475,
  },

  /* ── CASH & EQUIVALENTS ────────────────────────────────── */
  {
    id: "CBN182",
    name: "T-Bills 182-Day (May 2026)",
    assetClass: "Cash",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Central Bank of Nigeria",
    quantity: 1,
    costPrice: 18_200,
    costBasis: 18_200,
    marketValue: 18_200,
    ytdReturn: 0.09,
    beta: 0.0,
  },
  {
    id: "CBN91",
    name: "T-Bills 91-Day (Apr 2026)",
    assetClass: "Cash",
    sector: "Sovereign",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Central Bank of Nigeria",
    quantity: 1,
    costPrice: 12_000,
    costBasis: 12_000,
    marketValue: 12_000,
    ytdReturn: 0.088,
    beta: 0.0,
  },

  /* ── ALTERNATIVES ──────────────────────────────────────── */
  {
    id: "SFJ",
    name: "Strategic FinTech JV",
    assetClass: "Alternatives",
    sector: "Technology",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Heirs Holdings / Partners",
    quantity: 1,
    costPrice: 6_800,
    costBasis: 6_800,
    marketValue: 8_200,
    ytdReturn: 0.172,
    beta: 1.22,
  },
  {
    id: "LIF",
    name: "Lagos Infrastructure Fund",
    assetClass: "Alternatives",
    sector: "Infrastructure",
    geography: "Nigeria",
    currency: "NGN",
    issuer: "Lagos State / Partners",
    quantity: 1,
    costPrice: 28_400,
    costBasis: 28_400,
    marketValue: 32_600,
    ytdReturn: 0.148,
    beta: 0.78,
  },
];
