import type { Transaction } from "../types";

export const TRANSACTIONS: Transaction[] = [
  {
    id: "TXN-0241",
    date: "2026-05-25",
    type: "Buy",
    holdingId: "FGNB33",
    assetName: "FGN Bond 2033",
    quantity: 100,
    price: 29_250,
    amount: -2_925,
    status: "Settled",
    notes: "Duration extension trade, tactical fixed income overlay",
  },
  {
    id: "TXN-0240",
    date: "2026-05-25",
    type: "Sell",
    holdingId: "HBK",
    assetName: "Heritage Bank",
    quantity: 50_000_000,
    price: 16.0,
    amount: 800,
    status: "Settled",
    notes: "Partial exit, near target weight",
  },
  {
    id: "TXN-0239",
    date: "2026-05-24",
    type: "Rebalance",
    holdingId: "HPL",
    assetName: "Real Estate Portfolio",
    amount: 0,
    status: "Processing",
    notes: "Internal revaluation rebalance",
  },
  {
    id: "TXN-0238",
    date: "2026-05-23",
    type: "Dividend",
    holdingId: "TCP",
    assetName: "Transcorp Plc",
    amount: 420,
    status: "Settled",
    notes: "Final FY2025 dividend — ₦0.051/share",
  },
  {
    id: "TXN-0237",
    date: "2026-05-22",
    type: "Coupon",
    holdingId: "FGNB31",
    assetName: "FGN Bond 2031",
    amount: 1_178,
    status: "Settled",
    notes: "Semi-annual coupon @ 15.5% p.a.",
  },
  {
    id: "TXN-0236",
    date: "2026-05-20",
    type: "Buy",
    holdingId: "TCP",
    assetName: "Transcorp Plc",
    quantity: 10_000_000,
    price: 8.29,
    amount: -82.9,
    status: "Settled",
    notes: "Tactical top-up on pre-results momentum",
  },
  {
    id: "TXN-0235",
    date: "2026-05-19",
    type: "Maturity",
    holdingId: "CBN91",
    assetName: "T-Bills 91-Day",
    amount: 5_200,
    status: "Settled",
    notes: "Principal redemption — proceeds rolled into 182-day",
  },
  {
    id: "TXN-0234",
    date: "2026-05-15",
    type: "Buy",
    holdingId: "UCA",
    assetName: "United Capital Plc",
    quantity: 20_000_000,
    price: 15.19,
    amount: -303.8,
    status: "Settled",
  },
  {
    id: "TXN-0233",
    date: "2026-05-10",
    type: "Dividend",
    holdingId: "APG",
    assetName: "Africa Prudential Plc",
    amount: 174,
    status: "Settled",
    notes: "Interim dividend",
  },
  {
    id: "TXN-0232",
    date: "2026-05-08",
    type: "Capital Call",
    holdingId: "AGF3",
    assetName: "Africa Growth Fund III",
    amount: -3_280,
    status: "Settled",
    notes: "Capital call #3 — co-investment in Lagos data centre",
  },
  {
    id: "TXN-0231",
    date: "2026-04-30",
    type: "Coupon",
    holdingId: "DGB26",
    assetName: "Dangote Industries Bond",
    amount: 368,
    status: "Settled",
    notes: "Quarterly coupon @ 14.75%",
  },
  {
    id: "TXN-0230",
    date: "2026-04-22",
    type: "Buy",
    holdingId: "CBN182",
    assetName: "T-Bills 182-Day",
    amount: -5_000,
    status: "Settled",
    notes: "Cash deployment from matured 91-day proceeds",
  },
  {
    id: "TXN-0229",
    date: "2026-04-10",
    type: "Sell",
    holdingId: "TCP",
    assetName: "Transcorp Plc",
    quantity: 200_000_000,
    price: 7.95,
    amount: 1_590,
    status: "Settled",
    notes: "Partial profit-taking post Q1 results",
  },
  {
    id: "TXN-0228",
    date: "2026-03-28",
    type: "Buy",
    holdingId: "HTA",
    assetName: "Heirs Tower Abuja",
    amount: -4_200,
    status: "Settled",
    notes: "Completion payment on tower development",
  },
  {
    id: "TXN-0227",
    date: "2026-03-15",
    type: "Dividend",
    holdingId: "UCA",
    assetName: "United Capital Plc",
    amount: 280,
    status: "Settled",
  },
];
