/* ──────────────────────────────────────────────────────────────
   RATING SCALE — index = canonical rank
   Each rating string maps to an index (1 = best, 33 = default)
   Used to translate any agency rating → Moody or S&P equivalent
   ────────────────────────────────────────────────────────────── */
export interface RatingScaleRow {
  index: number;
  Moody: string;
  SP: string;
  Fitch: string;
  GCR: string;
  Agusto: string;
  Datapro: string;
}

export const RATING_SCALE: RatingScaleRow[] = [
  {
    index: 1,
    Moody: "Aaa",
    SP: "AAA",
    Fitch: "AAA",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 2,
    Moody: "Aa1",
    SP: "AA+",
    Fitch: "AA+",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 3,
    Moody: "Aa2",
    SP: "AA",
    Fitch: "AA",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 4,
    Moody: "Aa3",
    SP: "AA-",
    Fitch: "AA-",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 5,
    Moody: "A1",
    SP: "A+",
    Fitch: "A+",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 6,
    Moody: "A2",
    SP: "A",
    Fitch: "A",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 7,
    Moody: "A3",
    SP: "A-",
    Fitch: "A-",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 8,
    Moody: "Baa1",
    SP: "BBB+",
    Fitch: "BBB+",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 9,
    Moody: "Baa2",
    SP: "BBB",
    Fitch: "BBB",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 10,
    Moody: "Baa3",
    SP: "BBB-",
    Fitch: "BBB-",
    GCR: "-",
    Agusto: "-",
    Datapro: "-",
  },
  {
    index: 11,
    Moody: "Ba1",
    SP: "BB+",
    Fitch: "BB+",
    GCR: "AAA",
    Agusto: "AAA",
    Datapro: "AAA",
  },
  {
    index: 12,
    Moody: "Ba2",
    SP: "BB",
    Fitch: "BB",
    GCR: "AA+",
    Agusto: "AA+",
    Datapro: "AA+",
  },
  {
    index: 13,
    Moody: "Ba3",
    SP: "BB-",
    Fitch: "BB-",
    GCR: "AA",
    Agusto: "AA",
    Datapro: "AA",
  },
  {
    index: 14,
    Moody: "Ba3",
    SP: "BB-",
    Fitch: "BB-",
    GCR: "AA-",
    Agusto: "AA-",
    Datapro: "AA-",
  },
  {
    index: 15,
    Moody: "B1",
    SP: "B+",
    Fitch: "B+",
    GCR: "A+",
    Agusto: "A+",
    Datapro: "A+",
  },
  {
    index: 16,
    Moody: "B1",
    SP: "B+",
    Fitch: "B+",
    GCR: "A",
    Agusto: "A",
    Datapro: "A",
  },
  {
    index: 17,
    Moody: "B1",
    SP: "B+",
    Fitch: "B+",
    GCR: "A-",
    Agusto: "A-",
    Datapro: "A-",
  },
  {
    index: 18,
    Moody: "B2",
    SP: "B",
    Fitch: "B",
    GCR: "BBB+",
    Agusto: "BBB+",
    Datapro: "BBB+",
  },
  {
    index: 19,
    Moody: "B2",
    SP: "B",
    Fitch: "B",
    GCR: "BBB",
    Agusto: "BBB",
    Datapro: "BBB",
  },
  {
    index: 20,
    Moody: "B2",
    SP: "B",
    Fitch: "B",
    GCR: "BBB-",
    Agusto: "BBB-",
    Datapro: "BBB-",
  },
  {
    index: 21,
    Moody: "B3",
    SP: "B-",
    Fitch: "B-",
    GCR: "BB+",
    Agusto: "BB+",
    Datapro: "BB+",
  },
  {
    index: 22,
    Moody: "B3",
    SP: "B-",
    Fitch: "B-",
    GCR: "BB",
    Agusto: "BB",
    Datapro: "BB",
  },
  {
    index: 23,
    Moody: "Caa",
    SP: "CCC+",
    Fitch: "CCC+",
    GCR: "BB-",
    Agusto: "BB-",
    Datapro: "BB-",
  },
  {
    index: 24,
    Moody: "Caa",
    SP: "CCC+",
    Fitch: "CCC+",
    GCR: "B+",
    Agusto: "B+",
    Datapro: "B+",
  },
  {
    index: 25,
    Moody: "Caa",
    SP: "CCC",
    Fitch: "CCC",
    GCR: "B",
    Agusto: "B",
    Datapro: "B",
  },
  {
    index: 26,
    Moody: "Caa",
    SP: "CCC",
    Fitch: "CCC",
    GCR: "B-",
    Agusto: "B-",
    Datapro: "B-",
  },
  {
    index: 27,
    Moody: "Caa",
    SP: "CCC",
    Fitch: "CCC",
    GCR: "CCC+",
    Agusto: "CCC+",
    Datapro: "CCC+",
  },
  {
    index: 28,
    Moody: "Caa",
    SP: "CCC-",
    Fitch: "CCC-",
    GCR: "CCC",
    Agusto: "CCC",
    Datapro: "CCC",
  },
  {
    index: 29,
    Moody: "Caa",
    SP: "CCC-",
    Fitch: "CCC-",
    GCR: "CCC-",
    Agusto: "CCC-",
    Datapro: "CCC-",
  },
  {
    index: 30,
    Moody: "Ca-C",
    SP: "CC",
    Fitch: "CC",
    GCR: "CC",
    Agusto: "CC",
    Datapro: "CC",
  },
  {
    index: 31,
    Moody: "Ca-C",
    SP: "CC",
    Fitch: "CC",
    GCR: "CC",
    Agusto: "CC",
    Datapro: "CC",
  },
  {
    index: 32,
    Moody: "Ca-C",
    SP: "C",
    Fitch: "C",
    GCR: "C",
    Agusto: "C",
    Datapro: "C",
  },
  {
    index: 33,
    Moody: "D",
    SP: "SD/D",
    Fitch: "RD/D",
    GCR: "D",
    Agusto: "D",
    Datapro: "D",
  },
];

