import type { InstrumentType } from "../types";

export const ISSUERS: Partial<
  Record<InstrumentType, { issuer: string; sector: string }[]>
> = {
  "FGN Bond": [{ issuer: "FGN", sector: "Sovereign" }],
  "State Bond": [
    { issuer: "Lagos State", sector: "Government" },
    { issuer: "Abuja FCT", sector: "Government" },
    { issuer: "Kano State", sector: "Government" },
    { issuer: "Delta State", sector: "Government" },
    { issuer: "Akwa Ibom State", sector: "Government" },
    { issuer: "Bayelsa State", sector: "Government" },
    { issuer: "Ekiti State", sector: "Government" },
    { issuer: "Kwara State", sector: "Government" },
    { issuer: "Edo State", sector: "Government" },
  ],
  "Corporate Bond": [
    { issuer: "Dangote Cement", sector: "Industrials" },
    { issuer: "Airtel Africa", sector: "Telecoms" },
    { issuer: "GTBank", sector: "Banking" },
    { issuer: "Zenith Bank", sector: "Banking" },
    { issuer: "NNPC", sector: "Energy" },
    { issuer: "Seplat", sector: "Energy" },
    { issuer: "Lafarge", sector: "Industrials" },
    { issuer: "UBA", sector: "Banking" },
    { issuer: "Stanbic IBTC", sector: "Banking" },
    { issuer: "Julius Berger", sector: "Construction" },
    { issuer: "Dangote Sugar", sector: "FMCG" },
    { issuer: "WAPCO", sector: "Industrials" },
    { issuer: "Total Energies", sector: "Energy" },
    { issuer: "Coronation Merchant", sector: "Banking" },
    { issuer: "FCMB", sector: "Banking" },
    { issuer: "Polaris Bank", sector: "Banking" },
    { issuer: "Nova Merchant", sector: "Banking" },
    { issuer: "Wema Bank", sector: "Banking" },
    { issuer: "Okomu Oil", sector: "Agric" },
    { issuer: "CAP Plc", sector: "Industrials" },
  ],
  Eurobond: [
    { issuer: "FGN", sector: "Sovereign" },
    { issuer: "GTB", sector: "Banking" },
    { issuer: "Zenith", sector: "Banking" },
    { issuer: "Access", sector: "Banking" },
    { issuer: "UBA", sector: "Banking" },
    { issuer: "Dangote", sector: "Industrials" },
    { issuer: "NNPC", sector: "Energy" },
    { issuer: "Ecobank", sector: "Banking" },
    { issuer: "MTN Nigeria", sector: "Telecoms" },
  ],
  "T-Bill": [{ issuer: "CBN / FGN", sector: "Money Market" }],
  "Commercial Paper": [
    { issuer: "Dangote Cement", sector: "Money Market" },
    { issuer: "MTN Nigeria", sector: "Money Market" },
    { issuer: "Flour Mills", sector: "Money Market" },
    { issuer: "Nestle Nigeria", sector: "Money Market" },
    { issuer: "Nigerian Breweries", sector: "Money Market" },
  ],
  "Promissory Note": [
    { issuer: "FGN Promissory Note", sector: "Money Market" },
  ],
  "Bank Placement": [
    { issuer: "Access Bank", sector: "Money Market" },
    { issuer: "Zenith Bank", sector: "Money Market" },
    { issuer: "GTBank", sector: "Money Market" },
  ],
  "Fixed Deposit": [
    { issuer: "First Bank", sector: "Money Market" },
    { issuer: "FCMB", sector: "Money Market" },
    { issuer: "Stanbic IBTC", sector: "Money Market" },
  ],
  "Mutual Fund": [
    { issuer: "ARM Investment", sector: "Collective Investment" },
    { issuer: "Stanbic Money Market", sector: "Collective Investment" },
    { issuer: "FBN Heritage Fund", sector: "Collective Investment" },
  ],
  Equity: [
    { issuer: "GTBank", sector: "Banking" },
    { issuer: "Zenith Bank", sector: "Banking" },
    { issuer: "Nestle Nigeria", sector: "FMCG" },
    { issuer: "GTCO", sector: "Banking" },
    { issuer: "UACN", sector: "Conglomerate" },
    { issuer: "Dangote Cement", sector: "Industrials" },
  ],
};
