import jsPDF from "jspdf";
import type { DealSlip } from "../types";
import {
  approvedByName,
  dealNotional,
  dealSlipTitle,
  documentEconomicsFields,
  fmtNotionalCurrency,
  HEIRS_BRAND_RGB,
  registerRef,
  settlementDate,
  slipVersionLabel,
  submittedDate,
} from "../engine/slip-fields";

/**
 * PDF export - follows the jsPDF layout pattern in ifrs9/pages/reports.tsx
 * (portrait A4, brand-colour header bar, manual doc.text/doc.rect).
 */
export function downloadDealSlipPdf(slip: DealSlip): void {
  const e = slip.economics;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = 210;
  const margin = 20;
  let y = 32;

  // Header bar
  doc.setFillColor(...HEIRS_BRAND_RGB);
  doc.rect(0, 0, pageW, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("HEIRS QUANTA · INVESTMENT DEAL SLIP", margin, 12);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(slipVersionLabel(slip), pageW - margin - 40, 12);

  // Title block
  doc.setTextColor(26, 26, 46);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  const titleLines = doc.splitTextToSize(dealSlipTitle(e), pageW - margin * 2) as string[];
  doc.text(titleLines, margin, y);
  y += titleLines.length * 6 + 2;

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 120);
  doc.text(`${slip.id}  ·  ${slip.status}  ·  ${e.portfolioBook}`, margin, y);
  y += 8;

  doc.setDrawColor(220, 220, 230);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  // Notional callout box
  doc.setFillColor(255, 245, 246);
  doc.setDrawColor(200, 16, 46);
  doc.roundedRect(margin, y, pageW - margin * 2, 16, 2, 2, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(200, 16, 46);
  doc.text("NOTIONAL AMOUNT", margin + 4, y + 5);
  doc.setFontSize(13);
  doc.setTextColor(26, 26, 46);
  doc.text(fmtNotionalCurrency(dealNotional(e), e.currency), margin + 4, y + 12);
  y += 22;

  // Metadata grid (2 columns)
  const meta: [string, string][] = [
    ["Originator", slip.createdBy.name],
    ["Desk", slip.createdBy.role],
    ["Submitted", submittedDate(slip)],
    ["Approved by", approvedByName(slip)],
    ["Settlement", settlementDate(slip)],
    ["Register ref", registerRef(slip)],
  ];
  const colW = (pageW - margin * 2 - 8) / 2;
  doc.setFontSize(8);
  meta.forEach(([label, value], idx) => {
    const col = idx % 2;
    const row = Math.floor(idx / 2);
    const x = margin + col * (colW + 8);
    const rowY = y + row * 11;
    doc.setFont("helvetica", "bold");
    doc.setTextColor(120, 120, 130);
    doc.text(label.toUpperCase(), x, rowY);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 50);
    const valLines = doc.splitTextToSize(value, colW) as string[];
    doc.text(valLines, x, rowY + 4);
  });
  y += Math.ceil(meta.length / 2) * 11 + 6;

  doc.line(margin, y, pageW - margin, y);
  y += 7;

  // Economics & terms
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(26, 26, 46);
  doc.text("Economics & terms", margin, y);
  y += 6;

  const fields = documentEconomicsFields(e);
  doc.setFontSize(8.5);
  for (const f of fields) {
    if (y > 268) {
      doc.addPage();
      y = margin;
    }
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 110);
    doc.text(f.label, margin, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 40);
    const valLines = doc.splitTextToSize(f.value, pageW - margin - 58) as string[];
    doc.text(valLines, margin + 52, y);
    y += Math.max(5.5, valLines.length * 4.2);
    doc.setDrawColor(235, 235, 240);
    doc.line(margin, y - 1, pageW - margin, y - 1);
  }

  if (slip.documents.length > 0) {
    y += 4;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(26, 26, 46);
    doc.text("Attachments", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(60, 60, 70);
    for (const d of slip.documents) {
      doc.text(`• ${d.name}`, margin, y);
      y += 4;
    }
  }

  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 150);
  doc.text(
    "Generated by Heirs Quanta - Confidential. Official records are maintained in the investment register after approved settlement.",
    margin,
    285,
    { maxWidth: pageW - margin * 2 },
  );

  doc.save(`${slip.id}-deal-slip.pdf`);
}
